#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/env.sh"

usage() {
  cat <<'EOF'
Usage: scripts/wasm/build-deps.sh [options]

Build wasm dependency stack into PLAY/wasm-prefix:
  libgpg-error -> npth -> libgcrypt -> libassuan -> libksba

Options:
  --clean          Remove dependency build directories and rebuild.
  --force          Rebuild all dependencies even if stamps exist.
  --help           Show this help text.
EOF
}

require_tool() {
  local tool="$1"
  if ! command -v "$tool" >/dev/null 2>&1; then
    wasm_die "Missing required tool: $tool"
  fi
}

CLEAN=0
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)
      CLEAN=1
      shift
      ;;
    --force)
      FORCE=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      wasm_die "Unknown option: $1"
      ;;
  esac
done

require_tool emconfigure
require_tool emmake
require_tool emcc
require_tool emar
require_tool emranlib
require_tool emnm
require_tool "$PKG_CONFIG"

STAMP_DIR="$WASM_BUILD_DIR/stamps"
mkdir -p "$STAMP_DIR"

ensure_libgpg_error_lock_header() {
  local header="$GNUPG_WASM_REPO_ROOT/PLAY/src/libgpg-error/src/syscfg/lock-obj-pub.wasm32-unknown-emscripten.h"

  if [[ -f "$header" ]]; then
    return
  fi

  wasm_info "Creating missing libgpg-error lock header for $WASM_HOST"
  mkdir -p "$(dirname "$header")"
  cat >"$header" <<'EOF'
## lock-obj-pub.wasm32-unknown-emscripten.h
## Generated by scripts/wasm/build-deps.sh for Emscripten pthread builds.
## To be included by mkheader into gpg-error.h

typedef struct
{
  long _vers;
  union {
    volatile char _priv[24];
    long _x_align;
    long *_xp_align;
  } u;
} gpgrt_lock_t;

#define GPGRT_LOCK_INITIALIZER {1,{{0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0, \
                                    0,0,0,0,0,0,0,0}}}
##
## Local Variables:
## mode: c
## buffer-read-only: t
## End:
##
EOF
}

if [[ "$CLEAN" -eq 1 ]]; then
  wasm_info "Cleaning dependency build directories"
  rm -rf \
    "$WASM_BUILD_DIR/libgpg-error" \
    "$WASM_BUILD_DIR/npth" \
    "$WASM_BUILD_DIR/libgcrypt" \
    "$WASM_BUILD_DIR/libassuan" \
    "$WASM_BUILD_DIR/libksba" \
    "$STAMP_DIR/libgpg-error" \
    "$STAMP_DIR/npth" \
    "$STAMP_DIR/libgcrypt" \
    "$STAMP_DIR/libassuan" \
    "$STAMP_DIR/libksba"
fi

build_autotools_pkg() {
  local pkg="$1"
  shift

  local src_dir="$GNUPG_WASM_REPO_ROOT/PLAY/src/$pkg"
  local build_dir="$WASM_BUILD_DIR/$pkg"
  local log_file="$WASM_LOG_DIR/$pkg.log"
  local stamp_file="$STAMP_DIR/$pkg"
  local -a configure_env=()

  if [[ ! -x "$src_dir/configure" ]]; then
    wasm_die "Missing configure script for $pkg at $src_dir/configure"
  fi

  if [[ "$FORCE" -eq 0 && -f "$stamp_file" ]]; then
    wasm_info "Skipping $pkg (already built; use --force to rebuild)"
    return
  fi

  rm -rf "$build_dir"
  mkdir -p "$build_dir"

  if [[ "$pkg" == "libgcrypt" ]]; then
    # Emscripten currently does not provide a working getrandom/getentropy
    # symbol for direct linkage in this build profile.
    configure_env+=(
      "ac_cv_func_getrandom=no"
      "ac_cv_func_getentropy=no"
      "ac_cv_header_sys_random_h=no"
    )
  fi

  wasm_info "Configuring $pkg"
  {
    echo "== configure $pkg =="
    (
      cd "$build_dir"
      env "${configure_env[@]}" emconfigure "$src_dir/configure" \
        --host="$WASM_HOST" \
        --build="$WASM_BUILD_TRIPLET" \
        --prefix="$WASM_PREFIX" \
        "$@"
    )

    echo "== build $pkg =="
    emmake make -C "$build_dir" -j"$WASM_JOBS"

    echo "== install $pkg =="
    emmake make -C "$build_dir" install
  } 2>&1 | tee "$log_file"

  touch "$stamp_file"
}

ensure_libgpg_error_lock_header

build_autotools_pkg \
  libgpg-error \
  --enable-static \
  --disable-shared \
  --disable-doc \
  --disable-tests \
  --disable-nls

build_autotools_pkg \
  npth \
  --enable-static \
  --disable-shared \
  --disable-tests

build_autotools_pkg \
  libgcrypt \
  --enable-static \
  --disable-shared \
  --disable-doc \
  --disable-asm

build_autotools_pkg \
  libassuan \
  --enable-static \
  --disable-shared \
  --disable-doc

build_autotools_pkg \
  libksba \
  --enable-static \
  --disable-shared \
  --disable-doc

wasm_info "Dependency build complete"
wasm_info "Prefix: $WASM_PREFIX"
wasm_info "Logs:   $WASM_LOG_DIR"
